name: CI
on:
  pull_request:
    branches: [main, next]
jobs:
  lint:
    name: lint code
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - name: Install dependencies for testing
        run: pip install -r requirements-test.txt

      - name: Lint with black
        run: black --check .
